name = "tbc-bot"
main = "src/index.ts"
compatibility_date = "2025-03-01"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "kv"
id = "6c6bac6973c541db857cf65e458eb15b"
preview_id = "ef9f9960b01644589c3ab033526a3c33"

[vars]
ALLOWED_CHAT_ID = "5747246445"

[triggers]
crons = ["0 */12 * * *"]
